// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TPMS.Infrastructure.Persistence.Configurations;

#nullable disable

namespace TPMS.Infrastructure.Migrations
{
    [DbContext(typeof(TPMSDBContext))]
    partial class TPMSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TPMS.Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressID"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("OwnerID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Phone1")
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetId"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("AssetSubCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextServiceDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int?>("PropertyUnitId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PurchaseValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("AssetSubCategoryId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<int>("AssetCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DefaultUsefulLifeMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDepreciable")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresComplianceCheck")
                        .HasColumnType("boolean");

                    b.HasKey("AssetCategoryId");

                    b.ToTable("AssetCategories");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetMaintenance", b =>
                {
                    b.Property<int>("AssetMaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetMaintenanceId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetMaintenanceId");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetMaintenances");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetSubCategory", b =>
                {
                    b.Property<int>("AssetSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetSubCategoryId"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("AssetSubCategoryId");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("AssetSubCategories");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.CompanySetting", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TaxID")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("CompanyID");

                    b.ToTable("CompanySettings", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DepositMaster", b =>
                {
                    b.Property<int>("DepositMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepositMasterID"));

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeaseID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DepositMasterID");

                    b.HasIndex("LeaseID")
                        .IsUnique();

                    b.ToTable("DepositMasters");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DepositTransaction", b =>
                {
                    b.Property<int>("DepositTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepositTransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepositMasterID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DepositTransactionID");

                    b.HasIndex("DepositMasterID");

                    b.ToTable("DepositTransactions");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Dispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeId"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisputeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RaisedBy")
                        .HasColumnType("integer");

                    b.Property<int>("RaisedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DisputeId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DisputeNumber")
                        .IsUnique();

                    b.HasIndex("RaisedByUserId");

                    b.ToTable("Disputes", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeAttachment", b =>
                {
                    b.Property<int>("DisputeAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeAttachmentId"));

                    b.Property<int>("DisputeId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DisputeAttachmentId");

                    b.HasIndex("DisputeId", "DocumentId")
                        .IsUnique();

                    b.ToTable("DisputeAttachments", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeComment", b =>
                {
                    b.Property<int>("DisputeCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeCommentId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisputeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.HasKey("DisputeCommentId");

                    b.HasIndex("CommentedByUserId");

                    b.HasIndex("DisputeId");

                    b.ToTable("DisputeComments", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeResolution", b =>
                {
                    b.Property<int>("DisputeResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeResolutionId"));

                    b.Property<decimal?>("AdjustedAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("AdjustedInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("DisputeId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResolutionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolvedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("DisputeResolutionId");

                    b.HasIndex("DisputeId")
                        .IsUnique();

                    b.ToTable("DisputeResolutions", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<int>("DocumentCategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentCategoryName")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousDocumentID")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("DocumentID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("OwnerTypeID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentAccessLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogID"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Device")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("LogID");

                    b.HasIndex("DocumentID");

                    b.ToTable("DocumentAccessLogs", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentCategory", b =>
                {
                    b.Property<int>("DocumentCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DocumentCategoryID");

                    b.ToTable("DocumentCategories", (string)null);

                    b.HasData(
                        new
                        {
                            DocumentCategoryID = 1,
                            CategoryName = "Property Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 2,
                            CategoryName = "Tenant Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 3,
                            CategoryName = "Lease & Agreements",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 4,
                            CategoryName = "Financial Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 5,
                            CategoryName = "Owner/Landlord Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 6,
                            CategoryName = "Maintenance Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 7,
                            CategoryName = "Legal Documents",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentCategoryID = 8,
                            CategoryName = "Other / Misc.",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocumentCategoryID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DocumentTypeID");

                    b.HasIndex("DocumentCategoryID");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentUploadSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<int?>("DocumentCategoryID")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerTypeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer");

                    b.Property<int>("UploadedChunks")
                        .HasColumnType("integer");

                    b.HasKey("SessionId");

                    b.ToTable("DocumentUploadSessions");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.KYCType", b =>
                {
                    b.Property<int>("KYCTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KYCTypeID"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("KYCTypeID");

                    b.ToTable("KYCTypes");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Landlord", b =>
                {
                    b.Property<int>("LandlordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LandlordID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LandlordID");

                    b.ToTable("Landlords");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Lease", b =>
                {
                    b.Property<int>("LeaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaseID"));

                    b.Property<decimal?>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateMovedIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeductionReason")
                        .HasColumnType("text");

                    b.Property<decimal?>("Deductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DisputeNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<decimal?>("GuaranteedRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LandlordID")
                        .HasColumnType("integer");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LeaseNotes")
                        .HasColumnType("text");

                    b.Property<int>("LeaseType")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<decimal?>("OverdueAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("OverdueReason")
                        .HasColumnType("text");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PenaltyPolicyID")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeaseID");

                    b.HasIndex("LandlordID");

                    b.HasIndex("LeaseType");

                    b.HasIndex("PenaltyPolicyID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("Status");

                    b.HasIndex("TenantID");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseAlert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertID"));

                    b.Property<DateTime>("AlertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaseID")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlertID");

                    b.HasIndex("LeaseID");

                    b.ToTable("LeaseAlerts");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseRenewal", b =>
                {
                    b.Property<int>("LeaseRenewalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaseRenewalID"));

                    b.Property<decimal?>("AdditionalDeposit")
                        .HasColumnType("numeric");

                    b.Property<int>("LeaseID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NewDeposit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NewEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NewRent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NewStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("OldDeposit")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OldEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OldRent")
                        .HasColumnType("numeric");

                    b.Property<string>("RenewalReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RenewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RenewedBy")
                        .HasColumnType("integer");

                    b.HasKey("LeaseRenewalID");

                    b.HasIndex("LeaseID");

                    b.ToTable("LeaseRenewals");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseTermination", b =>
                {
                    b.Property<int>("LeaseTerminationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaseTerminationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("DamageCharges")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DepositAdjusted")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DepositRefunded")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaseID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OutstandingRent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SettledBy")
                        .HasColumnType("integer");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerminationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LeaseTerminationID");

                    b.HasIndex("LeaseID")
                        .IsUnique();

                    b.ToTable("LeaseTerminations");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.OwnerType", b =>
                {
                    b.Property<int>("OwnerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OwnerTypeID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("OwnerTypeID");

                    b.ToTable("OwnerTypes", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.PartyKYC", b =>
                {
                    b.Property<int>("PartyKYCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartyKYCID"));

                    b.Property<int?>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KYCNumber")
                        .HasColumnType("text");

                    b.Property<int>("KYCTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("integer");

                    b.HasKey("PartyKYCID");

                    b.ToTable("PartyKYCs");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.PenaltyPolicy", b =>
                {
                    b.Property<int>("PenaltyPolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PenaltyPolicyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PercentageOfRent")
                        .HasColumnType("numeric");

                    b.HasKey("PenaltyPolicyID");

                    b.ToTable("PenaltyPolicies", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("PermissionID");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PropertyID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LandlordID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PropertyID");

                    b.HasIndex("LandlordID");

                    b.HasIndex("PropertyName");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UserID1")
                        .HasColumnType("integer");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.HasIndex("UserID1");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RentSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("LeaseID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Penalty")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("ScheduleID");

                    b.HasIndex("LeaseID");

                    b.ToTable("RentSchedules");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RequiredDocument", b =>
                {
                    b.Property<int>("RequiredDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequiredDocumentID"));

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerTypeID")
                        .HasColumnType("integer");

                    b.HasKey("RequiredDocumentID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("OwnerTypeID");

                    b.HasIndex("OwnerTypeID", "DocumentTypeID")
                        .IsUnique();

                    b.ToTable("RequiredDocuments", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolePermissionID"));

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int?>("RoleID1")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID1");

                    b.HasIndex("RoleID", "PermissionID")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantID");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Asset", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.AssetSubCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetSubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetMaintenance", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Asset", "Asset")
                        .WithMany("Maintenances")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetSubCategory", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.AssetCategory", "AssetCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetCategory");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DepositMaster", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Lease", "Lease")
                        .WithOne("DepositMaster")
                        .HasForeignKey("TPMS.Domain.Entities.DepositMaster", "LeaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DepositTransaction", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.DepositMaster", "DepositMaster")
                        .WithMany("Transactions")
                        .HasForeignKey("DepositMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepositMaster");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Dispute", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TPMS.Domain.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("RaisedByUser");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeAttachment", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Dispute", "Dispute")
                        .WithMany("Attachments")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeComment", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.User", "CommentedByUser")
                        .WithMany()
                        .HasForeignKey("CommentedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.Dispute", "Dispute")
                        .WithMany("Comments")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedByUser");

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DisputeResolution", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Dispute", "Dispute")
                        .WithOne("Resolution")
                        .HasForeignKey("TPMS.Domain.Entities.DisputeResolution", "DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Document", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.OwnerType", "OwnerType")
                        .WithMany()
                        .HasForeignKey("OwnerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("OwnerType");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentAccessLog", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentType", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.DocumentCategory", "Category")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("DocumentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Lease", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Landlord", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordID");

                    b.HasOne("TPMS.Domain.Entities.PenaltyPolicy", "PenaltyPolicy")
                        .WithMany()
                        .HasForeignKey("PenaltyPolicyID");

                    b.HasOne("TPMS.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Landlord");

                    b.Navigation("PenaltyPolicy");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseAlert", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Lease", "Lease")
                        .WithMany("LeaseAlerts")
                        .HasForeignKey("LeaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseRenewal", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Lease", "Lease")
                        .WithMany("Renewals")
                        .HasForeignKey("LeaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.LeaseTermination", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Lease", "Lease")
                        .WithOne("Termination")
                        .HasForeignKey("TPMS.Domain.Entities.LeaseTermination", "LeaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Property", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Landlord", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RentSchedule", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Lease", "Lease")
                        .WithMany("RentSchedules")
                        .HasForeignKey("LeaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RequiredDocument", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.OwnerType", "OwnerType")
                        .WithMany()
                        .HasForeignKey("OwnerTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("OwnerType");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID1");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.User", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TPMS.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPMS.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DepositMaster", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Dispute", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Resolution")
                        .IsRequired();
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentCategory", b =>
                {
                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Landlord", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Lease", b =>
                {
                    b.Navigation("DepositMaster");

                    b.Navigation("LeaseAlerts");

                    b.Navigation("Renewals");

                    b.Navigation("RentSchedules");

                    b.Navigation("Termination");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("TPMS.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
